### ISSUE TITLE
Add GetUserStatus Method

### ISSUE THREAD

**Issue by markman623** [K2NE/K2NEServiceBroker#10]
Add GetUserStatus Method

**Comment by cyclops1982** [comment]
I'm assuming this is for Out of Office usage.

What would the input and output of this method be?

**Comment by markman623** [comment]
Will use the following method for this: SourceCode.Workflow.Management.WorkflowManagementServer.GetUserStatus()
Inputs are username (FQN?),
Output is an enum 'UserStatuses' with three values (Available, None, OOF) that will be returned in string format.
