### ISSUE TITLE
Issue with building solution in VS

### ISSUE THREAD

**Issue by mikerodionov** [K2NE/K2NEServiceBroker#107]
I have an issue building broker DLL from solution from Denallix box (v7/v8) - keep getting this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Automation' does not exist in the namespace 'System.Management' (are you missing an assembly reference?)	K2Field.K2NE.ServiceBroker	C:\K2NEServiceBroker-master\K2Field.K2NE.ServiceBroker\Helpers\PowerShell\PowerShellSerializationHelper.cs	5	Active

Adding different nugget packages does not help.

**Comment by panjkov** [comment]
Which VS version are you using?

**Comment by mikerodionov** [comment]
Enterprise 2015 Update 3

**Comment by cyclops1982** [comment]
Closing as i can't reproduce this.
