### ISSUE TITLE
Add ability to start processes with datafields

### ISSUE THREAD

**Issue by cyclops1982** [K2NE/K2NEServiceBroker#12]
We can start a process now, but not supply datafields.

This is a bit tricky as datafields are a collection. Current existing brokers use a format like:
"DataField1:Value1|DataField2:Value2"

Maybe we should look into JSON and/or JSON building functions like the web service brokers use...?

**Comment by cyclops1982** [comment]
Maybe we should input a json string or one of those serialization string so we can build up the string using the service broker as well.

**Comment by dudelis** [comment]
What if we can do the following:
1. Create a ServiceInstance configuration parameter where we can specify the list of workflows we want to start.
2. When creating the ServiceInstance the ServiceObject will dynamically create as many Start... methods as there are workflows.
3. And each method will dynamically create a list of input parameters as many as there are DataFields for each workflow?

Not sure if it is possible, but maybe we can at least think/discuss this option?
