### ISSUE TITLE
Build Fails when running UpdateBuildNR.ps1

### ISSUE THREAD

**Issue by markman623** [K2NE/K2NEServiceBroker#122]
The following error occurs:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "powershell.exe -file "C:\Users\Administrator\Desktop\K2NEServiceBroker-master\K2NEServiceBroker-master\\Solution Files\UpdateBuildNr.ps1"" exited with code 1.	K2Field.K2NE.ServiceBroker			

This is on 8.1 Core Lite, VS 2017

Fails on line:

$AssemInfo = split-path -Path $PSScriptRoot -parent

Due to the following issues:

https://stackoverflow.com/questions/44474074/powershell-psscriptroot-is-null

I believe the line should be changed to:

$AssemInfo = if ($psISE)
{
    Split-Path -Path $psISE.CurrentFile.FullPath -parent    
}
else
{
    split-path -Path $PSScriptRoot -parent
}

But have to test more.

**Comment by cyclops1982** [comment]
Pull requests are welcome! :)

**Comment by cyclops1982** [comment]
Can't reproduce this one on VS2017 to be honest. Did change something to the script, but that had nothing to do with $PSScriptROot.
