### ISSUE TITLE
ADO.NET query 2 Excel function does not export Number items correctly

### ISSUE THREAD

**Issue by cyclops1982** [K2NE/K2NEServiceBroker#124]
Hi,
If you have a query like:
SELECT * FROM Process_Instance

then the ID property in the resulting excel file is a text, and not a number. Initially this does not show very well, but if you copy/paste the export into a new excel, you will see warnings that you're using number values as text. THis means number formatting is not correctly applied and calculations (like sums) do not always work correctly

**Comment by markman623** [comment]
This needs to be done for double/decimal values also.

**Comment by cyclops1982** [comment]
Closed with pull request.
