### ISSUE TITLE
Project does not build on clean system

### ISSUE THREAD

**Issue by chevdor** [K2NE/K2NEServiceBroker#14]
Hi guys,

I just cloned the project and I tried building without any change.
here are the errors.
```
Error	6	The type or namespace name 'IHostableType' could not be found (are you missing a using directive or an assembly reference?)	c:\..\K2NEServiceBroker\K2Field.K2NE.ServiceBroker\K2NEServiceBroker.cs	14	59	K2Field.K2NE.ServiceBroker
Error	9	The type or namespace name 'IServerMarshaling' could not be found (are you missing a using directive or an assembly reference?)	c:\..\K2NEServiceBroker\K2Field.K2NE.ServiceBroker\K2NEServiceBroker.cs	184	73	K2Field.K2NE.ServiceBroker
Error	8	The type or namespace name 'IServiceMarshalling' could not be found (are you missing a using directive or an assembly reference?)	c:\..\K2NEServiceBroker\K2Field.K2NE.ServiceBroker\K2NEServiceBroker.cs	184	33	K2Field.K2NE.ServiceBroker
Error	5	The type or namespace name 'Logging' does not exist in the namespace 'SourceCode' (are you missing an assembly reference?)	c:\..\K2NEServiceBroker\K2Field.K2NE.ServiceBroker\Logger.cs	10	28	K2Field.K2NE.ServiceBroker
Error	7	The type or namespace name 'Logging' does not exist in the namespace 'SourceCode' (are you missing an assembly reference?)	c:\..\K2NEServiceBroker\K2Field.K2NE.ServiceBroker\Logger.cs	23	34	K2Field.K2NE.ServiceBroker
```

**Comment by cyclops1982** [comment]
I just cloned it again, for me it works.

Which version of K2 are you on? How are the project references set for you? Which version of VS?

**Comment by chevdor** [comment]
4.6.9 and VisualStudio 2013.
I fixed it in 73a9f6e4d1a1b64e9429bf60f46fc57b45cb77cf but you´d need to check if that still works on your side. I will submit a PR in a minute. It will include this change.

**Comment by cyclops1982** [comment]
Thanks for the pull request. I can't run 'cpack' Where to get that from?

**Comment by cyclops1982** [comment]
Pushed your branch for reference...

**Comment by chevdor** [comment]
You need to read the description of the PR :smile: 
It is explained there that in this version, I am still using cpack instead of nuget which means you need to install chocolatey first.

You can find a one liner at chocolatey.org. You copy it in an admin shell, get an espresso and by the time you are back, you have it all.

**Comment by cyclops1982** [comment]
Ah right. Sorry for that one :o

So, what does cpack do actually? Because i can see the powershell scripts - they don't' seem to need anything else?

As always, keeping dependencies to a minimum....

**Comment by chevdor** [comment]
cpack will put things together into a nuget package that is a little special because it contains a chocolateyInstall and chocolateyUninstall script.

Installing the package will unzip it somewhere and run the scripts for you without the user even having to know what powershell is.

So in short, it is indeed a new dependency but it brings a lot of interesting features such as version management, dedendencies, documentation (changelogs and links are in the package), ...

Try it and you will never go back :smile:
