### ISSUE TITLE
Changelog automation

### ISSUE THREAD

**Issue by chevdor** [K2NE/K2NEServiceBroker#17]
Not sure about you guys but I personnally hate writting changelog updates as much I love getting some.

There is an easy option for that, in short:
* First get the changelog **out** of the readme (if you still want it together at the end, using asciidoc instead of markdown can help)
* write your commit logs using conventional changelogs (see https://www.npmjs.com/package/conventional-changelog)
* install nodejs
* make a gulpfile.js with a 'changelog' task that will build the file for you!

I can assist if you need but not much time right now. 
First let me know if you are interested in such change or not.

There is one drawback, you need to add nodejs to your dev stack. IMO this is no big deal and it adds lots of cool possibilities regarding automatic packaging and publishing. I can only recommend it.

**Comment by cyclops1982** [comment]
After working with the project for a while, most pull requests are not so well organized that we can do this :(

**Comment by chevdor** [comment]
That´s the limitation of the method, everyone needs to write clean commit logs following the convention.

There is no magic, you write clean *before*, or *after*.

So if you don´t think this can apply, feel free to close this issue.

**Comment by cyclops1982** [comment]
I would love to be able to do this, but i don't want to limit people in sending a pull request because of non-clean commit messages. That's the main reason :)
