### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chevdor** [K2NE/K2NEServiceBroker#18]
Some documentation regarding what the broker actually really does woud be good.

**Comment by chevdor** [comment]
you can find a start in 25c5007cc8115f9e6f1107d9c16c07eb9a7e658d

**Comment by cyclops1982** [comment]
Great start - should we move it to a separate MD file and link from the readme.md?

**Comment by chevdor** [comment]
This is totally up to you. 
What I personally would do is to create a file called K2NEServiceBroker.adoc and do the doc in there using asciidoc. Asciidoc is very similar to md and if you like md you won´t have a problem to switch. Github also supports asciidoc.

The main benefit is the ability to "include" files. This is probably **not** for now but later when that broker grows, you will probably want to have a file for the client api, a file for the management api and also you will want to have all together as a single doc.
That exactly what md cannot do and where asciidoc works great:

* client-api.adoc
* management-api.doc
* and the k2neservicebroker.adoc file includes the previous with lines such as include::client-api.adoc[]

You can then read the doc directly in github, in your browser with the chrome extension for asciidoctor or generate some rtf, html, pdf, etc.... file.

**Comment by chevdor** [comment]
Easier to see in action: ce43ac7eb3090456ae40b436d785277c335e0b93

**Comment by cyclops1982** [comment]
I like that we can have includes, that makes it easier to edit/merge and so on.

Is there a way to generate a PDF from those docs?

**Comment by chevdor** [comment]
Yep, I love the include as well. Thinking further than the broker itself, that means you can also include the entire broker doc into a customer project.... just saying :)

Making PDFs is trivial on Linux and Mac. This is more painful on Windows unless you use a docker image. You can also install the tooling. It works but that´s no fun.

http://asciidoctor.org/docs/convert-asciidoc-to-pdf/

The doc over there is actually also written using Asciidoc.

**Comment by cyclops1982** [comment]
We've started on this with one of our later commits, just needs to be fully documented now :)

**Comment by cyclops1982** [comment]
The documentation is added, but not complete. I'm closing this one as i'd like to have specific items as to what needs to be documented.

I'm tempted to deny pull request if documentation is not included.
