### ISSUE TITLE
Lincense

### ISSUE THREAD

**Issue by timmes** [K2NE/K2NEServiceBroker#24]
We should put a license in place:
http://choosealicense.com/

MIT could be the right fit :)

**Comment by cyclops1982** [comment]
It's a difficult choice.

I'm currently voting for GPLv3 actually. Reasons for or against it?

**Comment by timmes** [comment]
Pro: 
- Requires anyone who distributes our code or a derivative work to make the source available under the same terms
- No Sublicensing
- Hold Liable

Contra:
- State Changes (Indication of significant code changes)

For a project like this it's the right fit to choose the GPLv3, IMHO. The MIT is more for simple, fun or smaller projects. So go ahead! :)

**Comment by cyclops1982** [comment]
Pull request welcome :-)
