### ISSUE TITLE
KPRX Unzipping and Analyzing

### ISSUE THREAD

**Issue by timmes** [K2NE/K2NEServiceBroker#4]
Functionality to get a specific process version from the K2 server, unzip and then anlyze the structure.

**Comment by cyclops1982** [comment]
What should the analysis do?

i"m thinking of:
- Show which wizards are being used
- show which SmartObjects are being used
- Show which environment fields are being used


What else should it do?

**Comment by timmes** [comment]
In addition to the above:
- Does it have a process wizard? If yes, which one (SP2010, SP2013, etc. ...)
- Are there datafields used which are not existent anymore?

**Comment by dudelis** [comment]
Are there datafields used which are not existent anymore?
- I am not sure it is possible. Since the workflow has been successfully built and deployed, when you download it from K2 server, it will have all the datafields. Otherwise it could not have been built.
Or I did not get the question right.

**Comment by timmes** [comment]
You're right, @dudelis!

**Comment by cyclops1982** [comment]
I've considered this, but i think the Service Broker might not be the correct place. It will probably too slow. I'll close the request now to reflect this.
