### ISSUE TITLE
Add SetInTheOffice Method

### ISSUE THREAD

**Issue by markman623** [K2NE/K2NEServiceBroker#8]
Add SetInTheOffice Method

**Comment by cyclops1982** [comment]
What would the input and output of this method be?

**Comment by markman623** [comment]
Will use the following method for this: SourceCode.Workflow.Management.WorkflowManagementServer.SetUserStatus()
Inputs are username (FQN?) and a status enum that will be hardcoded to 'None'
No output needed.
