### ISSUE TITLE
Add ListSharedUsers Method

### ISSUE THREAD

**Issue by markman623** [K2NE/K2NEServiceBroker#9]
Add ListSharedUsers Method

**Comment by cyclops1982** [comment]
What would the input and output of this method be?

**Comment by markman623** [comment]
Did not see this page before, will use as reference:

http://help.k2.com/onlinehelp/k2blackpearl/DevRef/4.6.9/default.htm#How_to_set_a_users_Out_of_Office_Status.html%3FTocPath%3DRuntime%2520APIs%2520and%2520Services%7CWorkflow%7CWorkflow%2520Client%2520API%7CWorkflow%2520Client%2520API%2520Samples%7C_____10

**Comment by markman623** [comment]
Added to my latest pull request.
