### ISSUE TITLE
Improvements to ErrorLog ServiceObject

### ISSUE THREAD

**Issue by cyclops1982** [K2NE/K2NEServiceBroker#98]
The current ErrorLog service object cannot be used in a loop because it doesn't  have a 'GetErrorById' (load) method and it does not have a autonumber indication on the ErrorId.

If we change this, it opens a few options for us to use this within some scenario's.

**Comment by hanuvanniekerk** [comment]
Added a new method called getErrorById. Created a pull request for maintainer of K2Ne Servicebroker to have a look at the changes made.
